version: '3.4'

services:
  rabbitmq-bus:
    image: rabbitmq:3.10.7-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 10s
      retries: 10

  mysql-db:
    image: mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty123!
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  tg-drive-host:
    build:
      context: aspnet-core
      dockerfile: ConsoleHost/Dockerfile
    environment:
      - TGDRIVE_MYSQL_CONNECTION_STRING=server=mysql-db;user=root;password=qwerty123!;database=tgdrivedb
      - TGDRIVE_LITEDB_CONNECTION_STRING=./tgdrive.db
      - TGDRIVE_BOT_TOKEN=6601174302:AAH1drTsxUXuRoZ1PAmO4hIT68zER4rt3RM
    depends_on:
      rabbitmq-bus:
        condition: service_healthy
      mysql-db:
        condition: service_healthy

  tg-drive-webapi:
    build:
      context: aspnet-core
      dockerfile: ServicesWebApi/Dockerfile
    environment:
      - TGDRIVE_MYSQL_CONNECTION_STRING=server=mysql-db;user=root;password=qwerty123!;database=tgdrivedb
      - TGDRIVE_LITEDB_CONNECTION_STRING=./tgdrive.db
      - TGDRIVE_BOT_TOKEN=6601174302:AAH1drTsxUXuRoZ1PAmO4hIT68zER4rt3RM
      - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/tgdrive.pfx
    ports:
      - "5050:5050"
      - "5051:5051"
    volumes:
      - ${TGDRIVE_CERT_PATH}:/https/
    depends_on:
      rabbitmq-bus:
        condition: service_healthy
      mysql-db:
        condition: service_healthy

  angular:
    build:
      context: angular
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tg-drive-host
      - tg-drive-webapi

volumes:
  mysqldb:
